language: scala
scala:
- 2.11.8
deploy:
  api_key:
    secure: QYYoYjCetj7W9xZgttHbzIWhLxPBNPTq9z5iBaGaExnqNUaIqbciP6UNceTkcb2nUz1/8FpHHHExi9kNWZJ9LflRZ4JYopTD5NrBxxfd/VCVtP4wlElWvoV/qQSAWEuqWHA++H2hdep71rXBcWqnaeS/pOcP9ZUEx4y3QhqnFQx4VSGKnUMnD7Z8UpaOFJKnYNOZq8Y5yqNmAgRRe5VvFBDbQ9zelxWEsGSZdxZQNm5TKcsgHJujnA+P+Sa+7HPV+aR9eFOtsDL1sKJ7cglBgHg1MjHrZvdRRoqf33TG0WhEiujPwywHTsLvcmVtBgKHS9cqRbQBSgJd60G4oyy+dhbQ6WvLdRJneM3TkhaMu2BZHF9AMCMUOvN9A9w3fbKVvP4pTit8WaUc2koB3KMIrAdK6/nl0bemQIBKtRxHVjXrKiBg/6NliAVyKWag0uUXwMmQMM7sZWjk3X2tM5NbLjukBi59FN3lyeTA1vAbtwsfXuJvrJvnipwJtxQLoRb1RPRlY6LFjiUmd3oiYTt4GfQ95wdibcRKUdYU4oNw5kzMbXnwB0K0nd91rIERPdqmeA4cb1V7o8ukFvDirzvZJI2qhm+4UR+HVIfxtMYCjSgzwlUEu49Oz29EvorgTGR8322zSN7xNZdAlhoquIPFl1uLoxcRlAMzfiU8XD6aLvg=
